### ISSUE TITLE
How to get photostream photos?

### ISSUE THREAD

**Issue by Astraport** [rivella50/ANE-CameraRoll#3]
Thanks for this ANE, but it can't get photostream on iOS devices.

**Comment by rivella50** [comment]
That was the first goal but the conversion of the images is just too slow for a photostream. Therefore a paging solution is the only solution at the moment.
If you have a faster way let me know.

**Comment by Astraport** [comment]
But I do not see such features in your example? I can only get a photos saved on my device. Is there a minimal example of how to access the photostream?

**Comment by rivella50** [comment]
Well you do not have direct access to the iOS photostream. With the ANE you can load a certain amount of images (limit and offset) which is what the example does.

**Comment by Astraport** [comment]
Hi!
How to get the full amount of photos in the camera roll? I try EVENT_COUNT_PHOTOS and countPhotos (), but it does not give me the result. 

UPDATE. Sorry, I hurried. Everything is perfect! Thank you.
